# snapshot (required)
# nettype (default:butterfly)
# piecestorage (defaul:./.venus/storage/)
# proxy (optional)
# TZ (optional)

version: '3'
services:
  auth:
    image: filvenus/venus-auth
    ports:
      - 8989:8989
    environment:
      - TZ=${TZ-UTC}
    volumes:
      - ./.venus/env:/env
      - ./.venus/root:/root
    network_mode: "host"
    entrypoint: "/script/compose.sh"

  venus:
    image: filvenus/venus
    ports:
      - 3453:3453
    network_mode: "host"
    volumes:
      - ${snapshot?snapshot.car is needed!}:/snapshot.car
      - ./.venus/env:/env
      - ./.venus/root:/root
    environment:
      - HTTPS_PROXY=${proxy}
      - nettype=${nettype-butterfly}
      - TZ=${TZ-UTC}
    entrypoint: "/script/compose.sh"
    depends_on:
      - auth

  gateway:
    image: filvenus/venus-gateway
    network_mode: "host"
    environment:
      - TZ=${TZ-UTC}
    volumes:
      - ./.venus/env:/env
      - ./.venus/root:/root
    ports:
      - 45132:45132

    command:
      [
        "--listen",
        "/ip4/0.0.0.0/tcp/45132",
        "run",
        "--auth-url",
        "http://127.0.0.1:8989"
      ]
    depends_on:
      - auth

  messager:
    image: filvenus/venus-messager
    network_mode: "host"
    ports:
      - 39812:39812
    volumes:
      - ./.venus/env:/env
      - ./.venus/root:/root
    environment:
      - TZ=${TZ-UTC}
    entrypoint: "/script/wait-for-it.sh 127.0.0.1:3453 -t 0  -- /script/compose.sh"
    depends_on:
      - auth
      - venus
      - gateway

  miner:
    image: filvenus/venus-miner
    network_mode: "host"
    ports:
      - 12308:12308
    volumes:
      - ./.venus/env:/env
      - ./.venus/root:/root
    environment:
      - nettype=${nettype-butterfly}
      - TZ=${TZ-UTC}
    entrypoint: "/script/wait-for-it.sh 127.0.0.1:3453 -t 0  -- /script/compose.sh"
    depends_on:
      - auth
      - venus
      - gateway

  market:
    image: filvenus/venus-market
    network_mode: "host"
    environment:
      - TZ=${TZ-UTC}
    ports:
      - 41235:41235
    volumes:
      - ./.venus/env:/env
      - ./.venus/root:/root
      - ${piecestorage-./.venus/storage/}:/PieceStorage

    entrypoint: "/script/wait-for-it.sh 127.0.0.1:3453 -t 0  -- /script/compose.sh"
    depends_on:
      - auth
      - venus
      - gateway
