name: Vuepress deploy
uses: jenkey2011/vuepress-deploy@1.0.1
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: filecoin-project/docs
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: yarn docs:build
        BUILD_DIR: docs/.vuepress/dist/